markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: clearskyabove
url: http://clearskyabove.com
description: A starter blog
twitter: clearskyabove
github: clearskyabove
gravatar_url: http://www.gravatar.com/avatar/98470a113b9e36a99359c12e7d9b0772.jpg